spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umc8th?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: springproject
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG

discord:
  webhook:
    url: https://discord.com/api/webhooks/1370362301835776053/Xb2ap4DWCfOSy06cd8-gRcgYqBOtP04LV1JCxG21ADwGix0xstruwGJmEhHGt-h04LfP
